//import axios from "axios";
import moment from "moment/moment";
import { gantt } from "dhtmlx-gantt";

export const state = {
    projectList: {
        'FAB0d41d5b5d22c': {
            id: "FAB0d41d5b5d22c",
            time: "Updated 3hrs ago",
            client: 'Conixi',
            favourite: false,
            img: require("@/assets/images/brands/slack.png"),
            label: "Conixi - Admin & Dashboard",
            category: "Technology",
            subCategory: "Design and Development",
            skills: ["UI", "HTML", "CSS", "Vue"],
            services: [
                "Build project dashboard",
                "Deploy Admin section"
            ],
            description: "Build project dashboard plus admin section.",
            number: "18/42",
            progressBar: "34%",
            status: "Testing",
            priority: "High",
            tasks: [
                {
                    id: 1,
                    type: gantt.config.types.project, 
                    text: "Project Scoping & Design",
                    progress: 0.4,
                    open: true,
                    duration: "12",
                    start_date: moment().subtract(15, "days"),
                    payment: 0,
                    parent: null,
                    status: "unpaid",
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 2,
                    type: gantt.config.types.milestone, 
                    text: "Client Workshops",
                    start_date: moment().subtract(10, "days"),
                    duration: "8",
                    progress: 0.6,
                    parent: "1",
                    open: true,
                    payment: 1000,
                    status: "paid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 3,
                    type: gantt.config.types.project, 
                    text: "Specifications",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: "1",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    type: gantt.config.types.milestone,
                    text: "Specification Signoff",
                    start_date: moment().subtract(2, "days"),
                    duration: "6",
                    parent: "1",
                    progress: 0.5,
                    open: true,
                    payment: 1000,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    type: gantt.config.types.project, 
                    text: "Design & Development",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: null,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 5,
                    type: gantt.config.types.project, 
                    text: "Database Design & Development",
                    start_date: moment().add(12, "days"),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 6,
                    type: gantt.config.types.project, 
                    text: "API Development",
                    start_date: moment(),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 7,
                    type: gantt.config.types.project, 
                    text: "Standard Supporting Services",
                    start_date: moment().add(4, "days"),
                    duration: "8",
                    parent: "3",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 8,
                    type: gantt.config.types.project, 
                    text: "Main Admin Development",
                    start_date: moment().add(12, "days"),
                    duration: "5",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 9,
                    type: gantt.config.types.project, 
                    text: "Admin Testing",
                    start_date: moment().add(13, "days"),
                    duration: "4",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 10,
                    type: gantt.config.types.milestone,
                    text: "Admin Go-Live",
                    start_date: moment().add(15, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 4000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 11,
                    type: gantt.config.types.project, 
                    text: "Dashboard Development",
                    start_date: moment().add(5, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 12,
                    type: gantt.config.types.milestone,
                    text: "Dashboard Go-Live",
                    start_date: moment().add(7, "days"),
                    duration: "5",
                    parent: "11",
                    progress: 1,
                    open: true,
                    payment: 2000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
            ],
            members: [
                {
                    name: "Laura Van Zyl",
                    img: require("@/assets/images/users/avatar-2.jpg"),
                    projects: 2,
                    tasks: 12
                },
                {
                    name: "Alex Raubitschek",
                    img: require("@/assets/images/users/avatar-3.jpg"),
                    projects: 2,
                    tasks: 9
                }
            ],
            suppliers: [
                {
                    name: "DMax Design",
                    img: require("@/assets/images/companies/img-2.png"),
                }
            ],
            subItem: [{
                id: 1,
                imgFooter: require("@/assets/images/users/avatar-2.jpg")
            },
            {
                id: 2,
                imgNumber: "+"
            },
            ],
            createdDate: "10 Aug, 2022",
            dueDate: "10 Feb, 2023",
        },
        '6A7EdDEA9FaDC52': {
            id: "6A7EdDEA9FaDC52",
            time: "Last update : 08 May",
            client: 'Luton BC',
            favourite: false,
            img: require("@/assets/images/brands/dribbble.png"),
            label: "Redesign - Landing page",
            category: "Technology",
            subCategory: "Website",
            skills: ["UI", "Graphic Design", "Website Dev"],
            services: [
                "Landing Page Re-design",
                "Materials to support Development"
            ],
            description: "Re-design a landing page as per abc minimal design.",
            number: "22/56",
            progressBar: "54%",
            status: "In Progress",
            priority: "Medium",
            tasks: [
                {
                    id: 1,
                    text: "Project Scoping & Design",
                    progress: 0.4,
                    open: true,
                    duration: "12",
                    start_date: moment().subtract(15, "days"),
                    payment: 0,
                    parent: null,
                    status: "unpaid",
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 2,
                    text: "Client Workshops",
                    start_date: moment().subtract(10, "days"),
                    duration: "8",
                    progress: 0.6,
                    parent: "1",
                    open: true,
                    payment: 1000,
                    status: "paid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 3,
                    text: "Specifications",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: "1",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    text: "Specification Signoff",
                    start_date: moment().subtract(2, "days"),
                    duration: "6",
                    parent: "1",
                    progress: 0.5,
                    open: true,
                    payment: 1000,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    text: "Design & Development",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: null,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 5,
                    text: "Database Design & Development",
                    start_date: moment().add(12, "days"),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 6,
                    text: "API Development",
                    start_date: moment(),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 7,
                    text: "Standard Supporting Services",
                    start_date: moment().add(4, "days"),
                    duration: "8",
                    parent: "3",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 8,
                    text: "Main Admin Development",
                    start_date: moment().add(12, "days"),
                    duration: "5",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 9,
                    text: "Admin Testing",
                    start_date: moment().add(13, "days"),
                    duration: "4",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 10,
                    text: "Admin Go-Live",
                    start_date: moment().add(15, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 4000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 11,
                    text: "Dashboard Development",
                    start_date: moment().add(5, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 12,
                    text: "Dashboard Go-Live",
                    start_date: moment().add(7, "days"),
                    duration: "5",
                    parent: "11",
                    progress: 1,
                    open: true,
                    payment: 2000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
            ],
            members: [
                {
                    name: "Laura Van Zyl",
                    img: require("@/assets/images/users/avatar-2.jpg"),
                    projects: 2,
                    tasks: 12
                },
                {
                    name: "Alex Raubitschek",
                    img: require("@/assets/images/users/avatar-3.jpg"),
                    projects: 2,
                    tasks: 9
                }
            ],
            suppliers: [
                {
                    name: "DMax Design",
                    img: require("@/assets/images/companies/img-2.png"),
                }
            ],
            subItem: [{
                id: 1,
                imgFooter: require("@/assets/images/users/avatar-3.jpg")
            },
            {
                id: 2,
                imgNumber: "S",
                bgColor: "secondary"
            },
            {
                id: 3,
                imgFooter: require("@/assets/images/users/avatar-4.jpg")
            },
            {
                id: 4,
                imgNumber: "+"
            },
            ],
            createdDate: "18 Sep, 2022",
            dueDate: "10 Mar, 2023",
        },
        '0bFED1ADAE4bcC1': {
            id: "0bFED1ADAE4bcC1",
            client: 'Hampshire CC',
            time: "Last update : 21 Jun",
            favourite: false,
            img: require("@/assets/images/brands/dropbox.png"),
            label: "Project App",
            category: "Technology",
            subCategory: "Development",
            skills: ["System Design", "Database Design", "Vue", "NestJS"],
            services: [
                "Project Management Application",
                "Task Management Application",
            ],
            description: "Create an application for project management and task management.",
            number: "20/34",
            progressBar: "78%",
            status: "In Progress",
            priority: "High",
            tasks: [
                {
                    id: 1,
                    text: "Project Scoping & Design",
                    progress: 0.4,
                    open: true,
                    duration: "12",
                    start_date: moment().subtract(15, "days"),
                    payment: 0,
                    parent: null,
                    status: "unpaid",
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 2,
                    text: "Client Workshops",
                    start_date: moment().subtract(10, "days"),
                    duration: "8",
                    progress: 0.6,
                    parent: "1",
                    open: true,
                    payment: 1000,
                    status: "paid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 3,
                    text: "Specifications",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: "1",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    text: "Specification Signoff",
                    start_date: moment().subtract(2, "days"),
                    duration: "6",
                    parent: "1",
                    progress: 0.5,
                    open: true,
                    payment: 1000,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 4,
                    text: "Design & Development",
                    start_date: moment().subtract(5, "days"),
                    duration: "8",
                    parent: null,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 5,
                    text: "Database Design & Development",
                    start_date: moment().add(12, "days"),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 6,
                    text: "API Development",
                    start_date: moment(),
                    duration: "7",
                    parent: "2",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 7,
                    text: "Standard Supporting Services",
                    start_date: moment().add(4, "days"),
                    duration: "8",
                    parent: "3",
                    progress: 0.6,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 8,
                    text: "Main Admin Development",
                    start_date: moment().add(12, "days"),
                    duration: "5",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 9,
                    text: "Admin Testing",
                    start_date: moment().add(13, "days"),
                    duration: "4",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 10,
                    text: "Admin Go-Live",
                    start_date: moment().add(15, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 4000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 11,
                    text: "Dashboard Development",
                    start_date: moment().add(5, "days"),
                    duration: "3",
                    parent: "4",
                    progress: 0.5,
                    open: true,
                    payment: 0,
                    status: "due",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
                {
                    id: 12,
                    text: "Dashboard Go-Live",
                    start_date: moment().add(7, "days"),
                    duration: "5",
                    parent: "11",
                    progress: 1,
                    open: true,
                    payment: 2000,
                    status: "unpaid",
                    changePayment: false,
                    changeStatus: false,
                    changeDate: false,
                    changeDescription: false,
                },
            ],
            members: [
                {
                    name: "Laura Van Zyl",
                    img: require("@/assets/images/users/avatar-2.jpg"),
                    projects: 2,
                    tasks: 12
                },
                {
                    name: "Derek Macrae",
                    img: require("@/assets/images/users/derekm.jpg"),
                    projects: 2,
                    tasks: 11
                }
            ],
            suppliers: [
                {
                    name: "DMax Design",
                    img: require("@/assets/images/companies/img-2.png"),
                }
            ],
            subItem: [{
                id: 1,
                imgNumber: "K",
                bgColor: "info"
            },
            {
                id: 2,
                imgNumber: "M",
                bgColor: "danger"
            },
            {
                id: 3,
                imgNumber: "+"
            },
            ],
            createdDate: "03 Aug, 2022",
            dueDate: "11 Apr, 2023",
        },
    },
};

export const mutations = {
    updateProject(state, payload) {
        console.log('updateProject: ', payload.id)
        Object.assign(state.projectList[payload.id], payload.updates);
    },
    updateProjectTask(state, payload) {
        console.log('updateProjectTask: ' + payload.id + ', task: ' + payload.taskId)
        const selTask = state.projectList[payload.id].tasks.find(task => task.id === payload.taskId)
        if(payload.updates.changePayment !== undefined) selTask.changePayment = payload.updates.changePayment;
        if(payload.updates.payment !== undefined) selTask.payment = payload.updates.payment;
    },
    deleteProject(state, id) {
        delete state.projectList[id];
    },
    createProject(state, payload) {
        console.log('createProject: ', payload)
        state.projectList[payload.id] = payload;
    }
};

export const actions = {
    updateProject({ commit }, payload) {
        console.log('updateProject(a): ', payload.id)
        commit('updateProject', payload)
    },
    updateProjectTask({ commit }, payload) {
        console.log('updateProjectTask(a): ', payload.id)
        commit('updateProjectTask', payload)
    },
    deleteProject({ commit }, id) {
        commit('deleteProject', id)
    },
    createProject({ commit }, payload) {
        commit('createProject', payload)
    }
};

export const getters = {
    projectList: state => state.projectList,
    //    project: state => state.projectList[id]
};
