<template>
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="myExtraLargeModalLabel">
            GENERAL SERVICE AGREEMENT
            </h5>
            <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
            ></button>
        </div>
        <div class="modal-body">
            <h6 class="fs-17 md-2">
            THIS GENERAL SERVICE AGREEMENT (the "Agreement") is dated this
            {{ props.todayDate }}.
            </h6>
            <div class="row mt-4">
            <div class="col">
                <h5 class="fs-14">CLIENT</h5>
                <p class="mb-0">CSG</p>
                <p class="mb-0">Hampshire</p>
                <p>(the "Client")</p>
            </div>
            <div class="col">
                <h5 class="fs-14">CONTRACTOR</h5>
                <p class="mb-0">{{userOrg}}</p>
                <p class="mb-0">St Albans</p>
                <p>(the "Contractor")</p>
            </div>
            </div>
            <section>
            <h6 class="fs-16 my-3 mt-0">BACKGROUND</h6>
            <p>
                <ol>
                    <li>The Client is of the opinion that the Contractor has the necessary qualifications,
                        experience and abilities to provide services to the Client.</li>
                    <li>The Contractor is agreeable to providing such services to the Client on the terms and
                        conditions set out in this Agreement.</li>
                </ol>
            </p>
            </section>
            <section class="mt-1">
                <p><b>IN CONSIDERATION OF</b> the matters described above and of the mutual benefits and obligations set forth in this Agreement,
                the receipt and sufficiency of which consideration is hereby acknowledged, the Client and the Contractor
                (individually the "Party" and collectively the "Parties" to this Agreement) agree as follows:</p>
            </section>
            <section class="mt-1">
            <h6 class="fs-16 my-3">SERVICES PROVIDED</h6>
            <p>
                <ol>
                    <li class="mb-2">The Client hereby agrees to engage the Contractor to provide the Client with the following services (the "Services"):
                        <ul class="mt-2">
                            <li class="text-muted mb-1" v-for="(service, index) in selProject.services" :key="index">
                                {{ service }}
                            </li>
                        </ul>
                    </li>
                    <li>The Services will also include any other tasks which the Parties may agree on.
                        The Contractor hereby agrees to provide such Services to the Client.
                    </li>
                </ol>
            </p>
            </section>
            <section class="mt-1">
            <h6 class="fs-16 my-3">TERM OF AGREEMENT</h6>
            <p>
                <ol>
                    <li>The term of this Agreement (the "Term") will begin on the date of this Agreement and will
                        remain in full force and effect until the completion of the Services, subject to earlier
                        termination as provided in this Agreement. The Term may be extended with the written consent of the Parties.
                    </li>
                    <li>In the event that either Party wishes to terminate this Agreement prior to the completion of the Services,
                        that Party will be required to provide 30 days' written notice to the other Party.
                    </li>
                </ol>
            </p>
            </section>
            <section class="mt-1">
            <h6 class="fs-16 my-3">PAYMENT ON MILESTONES</h6>
            <p>
                <ol>
                    <li>Payment will become due when the following milestones have been delivered and signed off by the client. A self-bill
                        will be made available.
                        <ol class="mt-2">
                            <li v-for="(item, index) in payItems" :key="index" class="mt-2 row">
                                <b class="col-6">{{ item.text }}</b>
                                <span class="col-4">due on {{ item.start_date.format('Do') + ' day of ' + item.start_date.format('MMMM, YYYY') }}</span>
                                <span class="col-2" style="text-align:right;padding-right:40px">£{{item.payment.toLocaleString("en-US")}}</span>
                            </li>
                        </ol>
                    </li>
                    <li class="mt-2">Invoices generated by the Client on behalf of the Contractor to the Client are due within 30 days of being raised.</li>
                    <li>In the event that this Agreement is terminated by the Client prior to completion of the Services but where the Services have been partially performed,
                        the Contractor will be entitled to pro rata payment of the Payment to the date of termination provided that there has been no
                        breach of contract on the part of the Contractor.</li>
                    <li>The Payment as stated in this Agreement does not include Value Added Tax.</li>
                    <li>The Contractor will be responsible for all income tax liabilities and National Insurance or similar contributions relating to the Payment and the Contractor
                        will indemnify the Client in respect of any such payments required to be made by the Client.</li>
                </ol>
            </p>
            </section>
            <section class="mt-1">
            <h6 class="fs-16 my-3">PERFORMANCE</h6>
            <p>
                <ol>
                <li>The Parties agree to do everything necessary to ensure that the terms of this Agreement take effect.
                </li>
                </ol>
            </p>
            </section>
            <section class="mt-1">
            <h6 class="fs-16 my-3">CURRENCY</h6>
            <p>
                <ol>
                <li>Except as otherwise provided in this Agreement, all monetary amounts referred to in this Agreement are in GBP.
                </li>
                </ol>
            </p>
            </section>
        </div>
        <div class="modal-footer">
            <a
            href="javascript:void(0);"
            class="btn btn-link link-success fw-medium"
            data-bs-dismiss="modal"
            ><i class="ri-close-line me-1 align-middle"></i> Close</a
            >
            <button type="button" class="btn btn-primary">Save as PDF</button>
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</template>

<script setup>
import { defineProps } from 'vue'
/*
    props
*/
    const props = defineProps({
        showModal: {
            type: Boolean,
            default: false
        },
        todayDate: {
            type: String,
            default: "No date prop"
        },
        selProject: {
            type: Object,
            default: null
        },
        paymentItems: {
            type: Object,
            default: null
        },
    })
    const userOrg = localStorage.getItem("userOrg");
    let payItems = props.selProject.tasks.data.filter((task) => task.payment);
    console.log(props.selProject)
</script>

<style>

</style>